# Generated by Django 3.2.12 on 2022-05-08 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserContactType',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.basemodel')),
                ('contact_type_name', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone')], default=None, max_length=10, null=True)),
                ('contact_type_value', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
            bases=('user.basemodel', models.Model),
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.basemodel')),
                ('type_name', models.CharField(max_length=50)),
            ],
            bases=('user.basemodel', models.Model),
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.basemodel')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
                ('contact_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.usercontacttype')),
                ('user_type_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.usertype')),
            ],
            bases=('user.basemodel', models.Model),
        ),
    ]
