# Generated by Django 3.2.12 on 2022-05-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='id',
            field=models.UUIDField(default=None, primary_key=True, serialize=False),
        ),
    ]
