# Generated by Django 3.2.12 on 2022-05-09 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_basemodel_id'),
        ('company', '0002_auto_20220509_1648'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='company.company'),
        ),
        migrations.AlterField(
            model_name='transactionstatus',
            name='description',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='ServicePriceCatalog',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.basemodel')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('company_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_price_catalogs', to='company.company')),
            ],
            bases=('user.basemodel', models.Model),
        ),
    ]
