# Generated by Django 3.2.12 on 2022-05-09 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.basemodel')),
                ('type_name', models.CharField(max_length=10)),
            ],
            bases=('user.basemodel', models.Model),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.basemodel')),
                ('clabe', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('account_number', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('account_type', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.accounttype')),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
            ],
            bases=('user.basemodel', models.Model),
        ),
    ]
