# Generated by Django 3.2.12 on 2022-05-09 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCode',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.basemodel')),
                ('country_code', models.CharField(max_length=2)),
                ('country_name', models.CharField(max_length=50)),
            ],
            bases=('user.basemodel', models.Model),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.basemodel')),
                ('street', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('colony', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_code_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.countrycode')),
            ],
            bases=('user.basemodel', models.Model),
        ),
    ]
