# Generated by Django 3.2.12 on 2022-05-09 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('address', '0002_address_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='company_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
    ]
